{% set name = "azure-mgmt-network" %}
{% set version = "2.3.0" %}
{% set sha256 = "bf2b459d055083eb5c8883b66828c1e7d917f2d3eef98bf65417022450c6ea7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - azure-common >=1.1
    - msrestazure >=0.4.20

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.network
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Network Resource Management Client Library for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
