{% set version = "1.7.1" %}

package:
  name: azure-mgmt-network
  version: {{ version }}

source:
  fn: azure-mgmt-network-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-mgmt-network/azure-mgmt-network-{{ version }}.zip
  md5: e19b92d147fbf527dea73539e39e1b7d
  
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
    - azure-mgmt-common
    
  run:
    - python
    - azure-mgmt-common

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.network
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Network Resource Management Client Library for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
