travis:
  secure:
    BINSTAR_TOKEN: uF9+TDyBODisVt6jqfzDccfxyr3BDdyLenu7EVGg8XZHp8t+j2cH2jDS1TVuod5nE1uc0TVia2nwor1Ex1DOFGs13CRX+g4craSPUT8wvz0Xfob2xI3E04QKSwskPofJgtiZT87bHikrU4tuDSfH/MD1qIbTi890oKOWne0fK12UR30i1DjlYd6y+JyGPsnQa7pfn1F3+mKTEyH75wU9twhCCKVQkcX0limfZwaIYr1gvJJkdevJ6RPZAFnz77jkaXoEPUVLubuNhViRshBSbJPv2H+Py6dFh3iaRtjBIuqNcye2pWz7ltl3+A0hrkCP7ht5+lPPNxMmS8BIMyAJwdNMWZQWsQ4Zr0sf2mzh2ekFSbdmxJi4SmTi9DSYshVqoWif0qjIkL5zjvx1UVLr7hctjE7ykBn7fmWOddVT68/b23dufs2Hqnk8tGEPniTQtNkc3/CDZhe/ZQOhzjfevH+t3DnKqd/nOcW8OWeeaBXPhbomIaqkrJWmPwi3ZF9tmpudSDUYOGHzvPi3s3jwa++dbnlnDxEZsFp/pqH0DBuKX9X/d1htEnkm47Ct6NjHUy0PQaO7sSxqQeGm4pe+sy73/Xwfe7eStkxfkv7F04z4AQqRWFq0Ywpo++GGDAgNC9sEcmPff+8vd39msimJDbrYyMr1DshPMR8cRhReOeE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
