travis:
  secure:
    BINSTAR_TOKEN: OjDi+Aj6SDQhARwESApEx3DS0SK2MrCQA74BlwTi3neoqKmeiWnpHL5wGa1GUsunCrE2AQy+62V4w7OzwZH9sUMqb6GK9fr9+6A/TkY2WQ32YgbOOQsMGPeGLWhv//YRZUp8xZBZSW5m6TsYBvj3E4nIPji0MoNGmmbEb3XfA6qBd/rzDuV37IEexflWn4myRznw4ji601Hwukz6YXNjXOYnbadj1Tp9SIcyIZLzESxb7Rz3IpYdxuAwUc1q4XkQ+72q4LrFmB8S7JFMtEmRE2JxanAXMYjInDou/zWw18DjlnYM9jqeoPjz/QJUmrBv+1yVlc0OIoEUeaPu2PU4PvZicGO5M8j8thbvytuUWzkTHtaCu4EpCbUs/KPdOpTag61XLbhsmLTwIERpxvUF2IZvCCA+Z3NlwMTqQR++ekfmHp8DWQ4be9m2VDYm1npIRTjxzEtthJMJFXL3+0Hf/onS++n+DMgENc5md44DsjqAzoh6VFPxerXUPZ1qG8T8yP/glihMiCO9HG+zuokSlsVwYF6m6iPLPbHLrt/frt8mYTkUeTIlzn4Ntkh4r2S8kEeHvLbm9cGxUr+Shbz/unBGrc262kCeNgaOR+WEwBfa0x7fUuZTzuS2mjQeRXZfd7qoafOtWrDx3k3+vIQfoDrL8ituA5Z727dfNksXqq8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
