travis:
  secure:
    BINSTAR_TOKEN: gfih4NPYffa3cyl/n+Q0pibEDWiIrTAprngS0aenNyvTe10h8D3n5fX+9fJtDCbnmSJBuDiHWwWuyFVm81ACMnC43xolhn6OT2LmUAor9uIgzzUyC6xTgrrnsaxjOdzNMgfyNkMRwac479F7SxdIFlNaCaHdOmMIDI6CaxvH0xeR41cvLv4L0XwjzLJoLL5E/sFeWB+U8Y/0RcrssYluNwLmeZBrQqVmt+njxpnnI5Rsi2YpwZ+jEKlmdOAzoKzVAvavnnLxno41LlFYuhSR20oKqzOn5h2KjJOJRPi6wq2gdMF/qAi+mWq4WyPAIajf4eHcGb/+ctu3cYJZWVQ48BR4OYButDParw8gVINjeHn7auYSvg1QJVx06ZK62ji6k2OkFpykg4ENWP8jcmCc8m46mbiMEkjVNVqqknZE9TeVutYmsjg1E2Q2mKF0qOUhi4LmmE7pAb6kEtFP7WZAD3oO4tw8KWz2xPeC0eDyErrJ1I3xmOjNJDUdbLYJruMw8Rogo9b26HdlvMXk+h4JqFFCIkMfg24Vp5NhN4KBER/X4197pmItOZYrnCHFt7Vosmz6q1R2Rp/Zb6DYZhf971X16z5CQk+7FEDSR5ENNpaXDpWvqVf9dsTpk3rb1nckQSAoWw6MkRmZzE4FhIfx/dPimWE28+DtVQuPbIe7gFM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
